name: dopetest_flutter
description: Dope test for Flutter.
publish_to: 'none' 

version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: IBMPlexMono
      fonts:
       - asset: IBMPlexMono-Regular.ttf